animation letters
htmlacademy-animation/824625-magic-vacation-1 pull request #5
Opened 2020-09-28 12:33 UTC by stolenwhale

2020-09-29 06:31 UTC, abeluzhenko requested changes
С самим заданием все прекрасно, но наш CI нетерпим к лишним пробелам. Вы можете принять мое изменение и все должно заработать.

2020-09-29 06:31 UTC, abeluzhenko commented on source/js/modules/animations/lettersAnimation.js
> +
```suggestion
```
Сборщик ругается на эту линию и PR невозможно будет влить в мастер.

2020-10-05 12:33 UTC, stolenwhale commented
Изменение с пробелом добавила. Можно теперь пул-реквест принять?

2020-10-05 13:15 UTC, abeluzhenko approved these changes

2020-10-05 13:16 UTC, merged